apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-garage
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-garage
  template:
    metadata:
      labels:
        app: app-garage
    spec:
      containers:
      - image: ramiro/appgarage:latest
        name: app-garage
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 0