apiVersion: v1
kind: Service
metadata:
  name: app-garage
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "app-garage"
    port: 8080
  selector:
    app: app-garage
